// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/authz/v1beta1/authz.proto

package authz

// import (
// 	fmt "fmt"
// 	_ "github.com/gogo/protobuf/gogoproto"
// 	proto "github.com/gogo/protobuf/proto"
// 	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
// 	_ "github.com/golang/protobuf/ptypes/timestamp"
// 	types "github.com/irisnet/core-sdk-go/codec/types"
// 	_ "github.com/regen-network/cosmos-proto"
// 	io "io"
// 	math "math"
// 	math_bits "math/bits"
// 	time "time"
// )

// // Reference imports to suppress errors if they are not otherwise used.
// var _ = proto.Marshal
// var _ = fmt.Errorf
// var _ = math.Inf
// var _ = time.Kitchen

// // This is a compile-time assertion to ensure that this generated file
// // is compatible with the proto package it is being compiled against.
// // A compilation error at this line likely means your copy of the
// // proto package needs to be updated.
// const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// // GenericAuthorization gives the grantee unrestricted permissions to execute
// // the provided method on behalf of the granter's account.
// type GenericAuthorization struct {
// 	// Msg, identified by it's type URL, to grant unrestricted permissions to execute
// 	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
// }

// func (m *GenericAuthorization) Reset()         { *m = GenericAuthorization{} }
// func (m *GenericAuthorization) String() string { return proto.CompactTextString(m) }
// func (*GenericAuthorization) ProtoMessage()    {}
// func (*GenericAuthorization) Descriptor() ([]byte, []int) {
// 	return fileDescriptor_544dc2e84b61c637, []int{0}
// }
// func (m *GenericAuthorization) XXX_Unmarshal(b []byte) error {
// 	return m.Unmarshal(b)
// }
// func (m *GenericAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
// 	if deterministic {
// 		return xxx_messageInfo_GenericAuthorization.Marshal(b, m, deterministic)
// 	} else {
// 		b = b[:cap(b)]
// 		n, err := m.MarshalToSizedBuffer(b)
// 		if err != nil {
// 			return nil, err
// 		}
// 		return b[:n], nil
// 	}
// }
// func (m *GenericAuthorization) XXX_Merge(src proto.Message) {
// 	xxx_messageInfo_GenericAuthorization.Merge(m, src)
// }
// func (m *GenericAuthorization) XXX_Size() int {
// 	return m.Size()
// }
// func (m *GenericAuthorization) XXX_DiscardUnknown() {
// 	xxx_messageInfo_GenericAuthorization.DiscardUnknown(m)
// }

// var xxx_messageInfo_GenericAuthorization proto.InternalMessageInfo

// // Grant gives permissions to execute
// // the provide method with expiration time.
// type Grant struct {
// 	Authorization *types.Any `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
// 	Expiration    time.Time  `protobuf:"bytes,2,opt,name=expiration,proto3,stdtime" json:"expiration"`
// }

// func (m *Grant) Reset()         { *m = Grant{} }
// func (m *Grant) String() string { return proto.CompactTextString(m) }
// func (*Grant) ProtoMessage()    {}
// func (*Grant) Descriptor() ([]byte, []int) {
// 	return fileDescriptor_544dc2e84b61c637, []int{1}
// }
// func (m *Grant) XXX_Unmarshal(b []byte) error {
// 	return m.Unmarshal(b)
// }
// func (m *Grant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
// 	if deterministic {
// 		return xxx_messageInfo_Grant.Marshal(b, m, deterministic)
// 	} else {
// 		b = b[:cap(b)]
// 		n, err := m.MarshalToSizedBuffer(b)
// 		if err != nil {
// 			return nil, err
// 		}
// 		return b[:n], nil
// 	}
// }
// func (m *Grant) XXX_Merge(src proto.Message) {
// 	xxx_messageInfo_Grant.Merge(m, src)
// }
// func (m *Grant) XXX_Size() int {
// 	return m.Size()
// }
// func (m *Grant) XXX_DiscardUnknown() {
// 	xxx_messageInfo_Grant.DiscardUnknown(m)
// }

// var xxx_messageInfo_Grant proto.InternalMessageInfo

// func init() {
// 	proto.RegisterType((*GenericAuthorization)(nil), "cosmos.authz.v1beta1.GenericAuthorization")
// 	proto.RegisterType((*Grant)(nil), "cosmos.authz.v1beta1.Grant")
// }

// func init() { proto.RegisterFile("cosmos/authz/v1beta1/authz.proto", fileDescriptor_544dc2e84b61c637) }

// var fileDescriptor_544dc2e84b61c637 = []byte{
// 	// 320 bytes of a gzipped FileDescriptorProto
// 	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcd, 0x4e, 0x02, 0x31,
// 	0x14, 0x85, 0xa7, 0x1a, 0x8d, 0xd6, 0x90, 0xc8, 0x64, 0x16, 0xc2, 0xa2, 0x10, 0x56, 0x2e, 0x64,
// 	0x1a, 0x74, 0xa7, 0x2b, 0x88, 0x09, 0x89, 0x89, 0x1b, 0xe2, 0xca, 0x8d, 0xe9, 0x0c, 0xb5, 0x34,
// 	0x32, 0x73, 0x49, 0xdb, 0x31, 0xc2, 0x53, 0xf0, 0x00, 0x3e, 0x86, 0x0f, 0x41, 0x5c, 0x11, 0x57,
// 	0xae, 0xfc, 0x61, 0x5e, 0xc4, 0xd0, 0x0e, 0x09, 0xe0, 0xee, 0xde, 0x73, 0xbf, 0x73, 0x4e, 0x9a,
// 	0xe2, 0x7a, 0x0c, 0x3a, 0x01, 0x4d, 0x59, 0x66, 0x06, 0x13, 0xfa, 0xdc, 0x8a, 0xb8, 0x61, 0x2d,
// 	0xb7, 0x85, 0x23, 0x05, 0x06, 0xfc, 0xc0, 0x11, 0xa1, 0xd3, 0x0a, 0xa2, 0x5a, 0x71, 0xea, 0x83,
// 	0x65, 0x68, 0x81, 0xd8, 0xa5, 0x5a, 0x13, 0x00, 0x62, 0xc8, 0xa9, 0xdd, 0xa2, 0xec, 0x91, 0x1a,
// 	0x99, 0x70, 0x6d, 0x58, 0x32, 0x2a, 0x80, 0x40, 0x80, 0x00, 0x67, 0x5c, 0x4e, 0x85, 0x5a, 0xd9,
// 	0xb6, 0xb1, 0x74, 0xec, 0x4e, 0x8d, 0x2b, 0x1c, 0x74, 0x79, 0xca, 0x95, 0x8c, 0xdb, 0x99, 0x19,
// 	0x80, 0x92, 0x13, 0x66, 0x24, 0xa4, 0xfe, 0x31, 0xde, 0x4d, 0xb4, 0x38, 0x41, 0x75, 0x74, 0x7a,
// 	0xd8, 0x5b, 0x8e, 0x97, 0xe5, 0x8f, 0xb7, 0x66, 0x69, 0x03, 0x6a, 0xbc, 0x22, 0xbc, 0xd7, 0x55,
// 	0x2c, 0x35, 0xfe, 0x2d, 0x2e, 0xb1, 0xf5, 0x93, 0x35, 0x1e, 0x9d, 0x07, 0xa1, 0x6b, 0x0e, 0x57,
// 	0xcd, 0x61, 0x3b, 0x1d, 0x77, 0xca, 0xef, 0xdb, 0x49, 0xbd, 0x4d, 0xb7, 0x7f, 0x8d, 0x31, 0x7f,
// 	0x19, 0x49, 0xe5, 0xb2, 0x76, 0x6c, 0x56, 0xf5, 0x5f, 0xd6, 0xdd, 0xea, 0xf1, 0x9d, 0x83, 0xd9,
// 	0x57, 0xcd, 0x9b, 0x7e, 0xd7, 0x50, 0x6f, 0xcd, 0xd7, 0xb9, 0x99, 0xfd, 0x12, 0x6f, 0xb6, 0x20,
// 	0x68, 0xbe, 0x20, 0xe8, 0x67, 0x41, 0xd0, 0x34, 0x27, 0xde, 0x3c, 0x27, 0xde, 0x67, 0x4e, 0xbc,
// 	0xfb, 0x33, 0x21, 0xcd, 0x20, 0x8b, 0xc2, 0x18, 0x12, 0x2a, 0x95, 0xd4, 0x29, 0x37, 0x34, 0x06,
// 	0xc5, 0x9b, 0xba, 0xff, 0xd4, 0x14, 0x40, 0x13, 0xe8, 0x67, 0x43, 0x5e, 0x7c, 0x5f, 0xb4, 0x6f,
// 	0x5b, 0x2f, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xd6, 0x1b, 0x49, 0xd5, 0x01, 0x00, 0x00,
// }

// func (m *GenericAuthorization) Marshal() (dAtA []byte, err error) {
// 	size := m.Size()
// 	dAtA = make([]byte, size)
// 	n, err := m.MarshalToSizedBuffer(dAtA[:size])
// 	if err != nil {
// 		return nil, err
// 	}
// 	return dAtA[:n], nil
// }

// func (m *GenericAuthorization) MarshalTo(dAtA []byte) (int, error) {
// 	size := m.Size()
// 	return m.MarshalToSizedBuffer(dAtA[:size])
// }

// func (m *GenericAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
// 	i := len(dAtA)
// 	_ = i
// 	var l int
// 	_ = l
// 	if len(m.Msg) > 0 {
// 		i -= len(m.Msg)
// 		copy(dAtA[i:], m.Msg)
// 		i = encodeVarintAuthz(dAtA, i, uint64(len(m.Msg)))
// 		i--
// 		dAtA[i] = 0xa
// 	}
// 	return len(dAtA) - i, nil
// }

// func (m *Grant) Marshal() (dAtA []byte, err error) {
// 	size := m.Size()
// 	dAtA = make([]byte, size)
// 	n, err := m.MarshalToSizedBuffer(dAtA[:size])
// 	if err != nil {
// 		return nil, err
// 	}
// 	return dAtA[:n], nil
// }

// func (m *Grant) MarshalTo(dAtA []byte) (int, error) {
// 	size := m.Size()
// 	return m.MarshalToSizedBuffer(dAtA[:size])
// }

// func (m *Grant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
// 	i := len(dAtA)
// 	_ = i
// 	var l int
// 	_ = l
// 	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Expiration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Expiration):])
// 	if err1 != nil {
// 		return 0, err1
// 	}
// 	i -= n1
// 	i = encodeVarintAuthz(dAtA, i, uint64(n1))
// 	i--
// 	dAtA[i] = 0x12
// 	if m.Authorization != nil {
// 		{
// 			size, err := m.Authorization.MarshalToSizedBuffer(dAtA[:i])
// 			if err != nil {
// 				return 0, err
// 			}
// 			i -= size
// 			i = encodeVarintAuthz(dAtA, i, uint64(size))
// 		}
// 		i--
// 		dAtA[i] = 0xa
// 	}
// 	return len(dAtA) - i, nil
// }

// func encodeVarintAuthz(dAtA []byte, offset int, v uint64) int {
// 	offset -= sovAuthz(v)
// 	base := offset
// 	for v >= 1<<7 {
// 		dAtA[offset] = uint8(v&0x7f | 0x80)
// 		v >>= 7
// 		offset++
// 	}
// 	dAtA[offset] = uint8(v)
// 	return base
// }
// func (m *GenericAuthorization) Size() (n int) {
// 	if m == nil {
// 		return 0
// 	}
// 	var l int
// 	_ = l
// 	l = len(m.Msg)
// 	if l > 0 {
// 		n += 1 + l + sovAuthz(uint64(l))
// 	}
// 	return n
// }

// func (m *Grant) Size() (n int) {
// 	if m == nil {
// 		return 0
// 	}
// 	var l int
// 	_ = l
// 	if m.Authorization != nil {
// 		l = m.Authorization.Size()
// 		n += 1 + l + sovAuthz(uint64(l))
// 	}
// 	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Expiration)
// 	n += 1 + l + sovAuthz(uint64(l))
// 	return n
// }

// func sovAuthz(x uint64) (n int) {
// 	return (math_bits.Len64(x|1) + 6) / 7
// }
// func sozAuthz(x uint64) (n int) {
// 	return sovAuthz(uint64((x << 1) ^ uint64((int64(x) >> 63))))
// }
// func (m *GenericAuthorization) Unmarshal(dAtA []byte) error {
// 	l := len(dAtA)
// 	iNdEx := 0
// 	for iNdEx < l {
// 		preIndex := iNdEx
// 		var wire uint64
// 		for shift := uint(0); ; shift += 7 {
// 			if shift >= 64 {
// 				return ErrIntOverflowAuthz
// 			}
// 			if iNdEx >= l {
// 				return io.ErrUnexpectedEOF
// 			}
// 			b := dAtA[iNdEx]
// 			iNdEx++
// 			wire |= uint64(b&0x7F) << shift
// 			if b < 0x80 {
// 				break
// 			}
// 		}
// 		fieldNum := int32(wire >> 3)
// 		wireType := int(wire & 0x7)
// 		if wireType == 4 {
// 			return fmt.Errorf("proto: GenericAuthorization: wiretype end group for non-group")
// 		}
// 		if fieldNum <= 0 {
// 			return fmt.Errorf("proto: GenericAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
// 		}
// 		switch fieldNum {
// 		case 1:
// 			if wireType != 2 {
// 				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
// 			}
// 			var stringLen uint64
// 			for shift := uint(0); ; shift += 7 {
// 				if shift >= 64 {
// 					return ErrIntOverflowAuthz
// 				}
// 				if iNdEx >= l {
// 					return io.ErrUnexpectedEOF
// 				}
// 				b := dAtA[iNdEx]
// 				iNdEx++
// 				stringLen |= uint64(b&0x7F) << shift
// 				if b < 0x80 {
// 					break
// 				}
// 			}
// 			intStringLen := int(stringLen)
// 			if intStringLen < 0 {
// 				return ErrInvalidLengthAuthz
// 			}
// 			postIndex := iNdEx + intStringLen
// 			if postIndex < 0 {
// 				return ErrInvalidLengthAuthz
// 			}
// 			if postIndex > l {
// 				return io.ErrUnexpectedEOF
// 			}
// 			m.Msg = string(dAtA[iNdEx:postIndex])
// 			iNdEx = postIndex
// 		default:
// 			iNdEx = preIndex
// 			skippy, err := skipAuthz(dAtA[iNdEx:])
// 			if err != nil {
// 				return err
// 			}
// 			if (skippy < 0) || (iNdEx+skippy) < 0 {
// 				return ErrInvalidLengthAuthz
// 			}
// 			if (iNdEx + skippy) > l {
// 				return io.ErrUnexpectedEOF
// 			}
// 			iNdEx += skippy
// 		}
// 	}

// 	if iNdEx > l {
// 		return io.ErrUnexpectedEOF
// 	}
// 	return nil
// }
// func (m *Grant) Unmarshal(dAtA []byte) error {
// 	l := len(dAtA)
// 	iNdEx := 0
// 	for iNdEx < l {
// 		preIndex := iNdEx
// 		var wire uint64
// 		for shift := uint(0); ; shift += 7 {
// 			if shift >= 64 {
// 				return ErrIntOverflowAuthz
// 			}
// 			if iNdEx >= l {
// 				return io.ErrUnexpectedEOF
// 			}
// 			b := dAtA[iNdEx]
// 			iNdEx++
// 			wire |= uint64(b&0x7F) << shift
// 			if b < 0x80 {
// 				break
// 			}
// 		}
// 		fieldNum := int32(wire >> 3)
// 		wireType := int(wire & 0x7)
// 		if wireType == 4 {
// 			return fmt.Errorf("proto: Grant: wiretype end group for non-group")
// 		}
// 		if fieldNum <= 0 {
// 			return fmt.Errorf("proto: Grant: illegal tag %d (wire type %d)", fieldNum, wire)
// 		}
// 		switch fieldNum {
// 		case 1:
// 			if wireType != 2 {
// 				return fmt.Errorf("proto: wrong wireType = %d for field Authorization", wireType)
// 			}
// 			var msglen int
// 			for shift := uint(0); ; shift += 7 {
// 				if shift >= 64 {
// 					return ErrIntOverflowAuthz
// 				}
// 				if iNdEx >= l {
// 					return io.ErrUnexpectedEOF
// 				}
// 				b := dAtA[iNdEx]
// 				iNdEx++
// 				msglen |= int(b&0x7F) << shift
// 				if b < 0x80 {
// 					break
// 				}
// 			}
// 			if msglen < 0 {
// 				return ErrInvalidLengthAuthz
// 			}
// 			postIndex := iNdEx + msglen
// 			if postIndex < 0 {
// 				return ErrInvalidLengthAuthz
// 			}
// 			if postIndex > l {
// 				return io.ErrUnexpectedEOF
// 			}
// 			if m.Authorization == nil {
// 				m.Authorization = &types.Any{}
// 			}
// 			if err := m.Authorization.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
// 				return err
// 			}
// 			iNdEx = postIndex
// 		case 2:
// 			if wireType != 2 {
// 				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
// 			}
// 			var msglen int
// 			for shift := uint(0); ; shift += 7 {
// 				if shift >= 64 {
// 					return ErrIntOverflowAuthz
// 				}
// 				if iNdEx >= l {
// 					return io.ErrUnexpectedEOF
// 				}
// 				b := dAtA[iNdEx]
// 				iNdEx++
// 				msglen |= int(b&0x7F) << shift
// 				if b < 0x80 {
// 					break
// 				}
// 			}
// 			if msglen < 0 {
// 				return ErrInvalidLengthAuthz
// 			}
// 			postIndex := iNdEx + msglen
// 			if postIndex < 0 {
// 				return ErrInvalidLengthAuthz
// 			}
// 			if postIndex > l {
// 				return io.ErrUnexpectedEOF
// 			}
// 			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Expiration, dAtA[iNdEx:postIndex]); err != nil {
// 				return err
// 			}
// 			iNdEx = postIndex
// 		default:
// 			iNdEx = preIndex
// 			skippy, err := skipAuthz(dAtA[iNdEx:])
// 			if err != nil {
// 				return err
// 			}
// 			if (skippy < 0) || (iNdEx+skippy) < 0 {
// 				return ErrInvalidLengthAuthz
// 			}
// 			if (iNdEx + skippy) > l {
// 				return io.ErrUnexpectedEOF
// 			}
// 			iNdEx += skippy
// 		}
// 	}

// 	if iNdEx > l {
// 		return io.ErrUnexpectedEOF
// 	}
// 	return nil
// }
// func skipAuthz(dAtA []byte) (n int, err error) {
// 	l := len(dAtA)
// 	iNdEx := 0
// 	depth := 0
// 	for iNdEx < l {
// 		var wire uint64
// 		for shift := uint(0); ; shift += 7 {
// 			if shift >= 64 {
// 				return 0, ErrIntOverflowAuthz
// 			}
// 			if iNdEx >= l {
// 				return 0, io.ErrUnexpectedEOF
// 			}
// 			b := dAtA[iNdEx]
// 			iNdEx++
// 			wire |= (uint64(b) & 0x7F) << shift
// 			if b < 0x80 {
// 				break
// 			}
// 		}
// 		wireType := int(wire & 0x7)
// 		switch wireType {
// 		case 0:
// 			for shift := uint(0); ; shift += 7 {
// 				if shift >= 64 {
// 					return 0, ErrIntOverflowAuthz
// 				}
// 				if iNdEx >= l {
// 					return 0, io.ErrUnexpectedEOF
// 				}
// 				iNdEx++
// 				if dAtA[iNdEx-1] < 0x80 {
// 					break
// 				}
// 			}
// 		case 1:
// 			iNdEx += 8
// 		case 2:
// 			var length int
// 			for shift := uint(0); ; shift += 7 {
// 				if shift >= 64 {
// 					return 0, ErrIntOverflowAuthz
// 				}
// 				if iNdEx >= l {
// 					return 0, io.ErrUnexpectedEOF
// 				}
// 				b := dAtA[iNdEx]
// 				iNdEx++
// 				length |= (int(b) & 0x7F) << shift
// 				if b < 0x80 {
// 					break
// 				}
// 			}
// 			if length < 0 {
// 				return 0, ErrInvalidLengthAuthz
// 			}
// 			iNdEx += length
// 		case 3:
// 			depth++
// 		case 4:
// 			if depth == 0 {
// 				return 0, ErrUnexpectedEndOfGroupAuthz
// 			}
// 			depth--
// 		case 5:
// 			iNdEx += 4
// 		default:
// 			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
// 		}
// 		if iNdEx < 0 {
// 			return 0, ErrInvalidLengthAuthz
// 		}
// 		if depth == 0 {
// 			return iNdEx, nil
// 		}
// 	}
// 	return 0, io.ErrUnexpectedEOF
// }

// var (
// 	ErrInvalidLengthAuthz        = fmt.Errorf("proto: negative length found during unmarshaling")
// 	ErrIntOverflowAuthz          = fmt.Errorf("proto: integer overflow")
// 	ErrUnexpectedEndOfGroupAuthz = fmt.Errorf("proto: unexpected end of group")
// )
